/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/transformers/utils/hub.py:105: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Loader not specified for model aari1995/German_Semantic_STS_V2, loading using sentence transformers.
No sentence-transformers model found with name aari1995/German_Semantic_STS_V2. Creating a new one with mean pooling.
Running evaluation for: aari1995/German_Semantic_STS_V2
Traceback (most recent call last):
  File "/home/tkl206/rag-structure-comparison/MultiModal/multiModalRun.py", line 38, in <module>
    model = mteb.get_model(model_name)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/mteb/models/overview.py", line 247, in get_model
    model = meta.load_model(**kwargs)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/mteb/model_meta.py", line 164, in load_model
    model: Encoder = loader(**kwargs)  # type: ignore
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/mteb/model_meta.py", line 51, in sentence_transformers_loader
    return SentenceTransformerWrapper(model=model_name, revision=revision, **kwargs)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/mteb/models/sentence_transformer_wrapper.py", line 37, in __init__
    self.model = SentenceTransformer(model, revision=revision, **kwargs)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 348, in __init__
    self.to(device)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 942, in _apply
    param_applied = fn(param)
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1341, in convert
    return t.to(
  File "/var/scratch/tkl206/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Expected a single True/False argument for expandable_segments
